#!/usr/bin/env bash
# Auto-update CHANGELOG.md on file changes via Claude Code PostToolUse hook.
# Reads JSON event data from stdin, extracts tool_name and file_path,
# then appends an entry to CHANGELOG.md.

set -euo pipefail

# --- Resolve project root ---
if [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then
  PROJECT_DIR="$CLAUDE_PROJECT_DIR"
else
  PROJECT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
fi

CHANGELOG="$PROJECT_DIR/CHANGELOG.md"

# --- Read stdin (PostToolUse JSON) ---
INPUT="$(cat)"

# --- Parse tool_name and file_path using jq (with grep/sed fallback) ---
if command -v jq &>/dev/null; then
  TOOL_NAME="$(echo "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null || true)"
  FILE_PATH="$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null || true)"
  BASH_CMD="$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null || true)"
else
  # Fallback: simple grep/sed parsing
  TOOL_NAME="$(echo "$INPUT" | grep -o '"tool_name"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*: *"//;s/"//')"
  FILE_PATH="$(echo "$INPUT" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*: *"//;s/"//')"
  BASH_CMD="$(echo "$INPUT" | grep -o '"command"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*: *"//;s/"//')"
fi

# --- Determine action and target ---
ACTION=""
TARGET=""

case "$TOOL_NAME" in
  Write)
    ACTION="Created"
    TARGET="$FILE_PATH"
    ;;
  Edit)
    ACTION="Edited"
    TARGET="$FILE_PATH"
    ;;
  Bash)
    # Only log git commit commands
    if echo "$BASH_CMD" | grep -q 'git commit'; then
      ACTION="Committed"
      # Extract commit message if possible
      COMMIT_MSG="$(echo "$BASH_CMD" | grep -oP '(?<=-m ")[^"]*' | head -1 || true)"
      if [ -z "$COMMIT_MSG" ]; then
        COMMIT_MSG="$(echo "$BASH_CMD" | grep -oP "(?<=-m ')[^']*" | head -1 || true)"
      fi
      if [ -n "$COMMIT_MSG" ]; then
        TARGET="$COMMIT_MSG"
      else
        TARGET="(git commit)"
      fi
    else
      exit 0
    fi
    ;;
  *)
    exit 0
    ;;
esac

# --- Exit if no action determined ---
[ -z "$ACTION" ] && exit 0

# --- Convert absolute path to project-relative ---
if [ -n "$TARGET" ] && [ "$ACTION" != "Committed" ]; then
  # Normalize Windows backslashes to forward slashes
  TARGET="$(echo "$TARGET" | sed 's|\\|/|g')"

  # Handle Git Bash /c/Users/... format
  TARGET="$(echo "$TARGET" | sed 's|^/c/|C:/|i')"

  # Normalize project dir too
  PROJ_NORM="$(echo "$PROJECT_DIR" | sed 's|\\|/|g' | sed 's|^/c/|C:/|i')"

  # Strip project dir prefix (case-insensitive on Windows)
  TARGET="$(echo "$TARGET" | sed "s|^${PROJ_NORM}/||i")"
  TARGET="$(echo "$TARGET" | sed "s|^${PROJ_NORM}||i")"
fi

# --- Anti-recursion: skip files that should not trigger changelog entries ---
case "$TARGET" in
  CHANGELOG.md|*/CHANGELOG.md) exit 0 ;;
  .claude/*) exit 0 ;;
  logs/*) exit 0 ;;
  data/state.json) exit 0 ;;
  data/last_run.json) exit 0 ;;
  *__pycache__*) exit 0 ;;
  *.tmp|*.pyc|nul) exit 0 ;;
esac

# --- Timestamp ---
TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null || date '+%Y-%m-%d %H:%M:%S')"

# --- Initialize CHANGELOG.md if it doesn't exist ---
if [ ! -f "$CHANGELOG" ]; then
  cat > "$CHANGELOG" <<'HEADER'
# Changelog

> Auto-generated by Claude Code hook. Each entry is recorded when a file is created, edited, or committed.

---

HEADER
fi

# --- Append entry ---
if [ "$ACTION" = "Committed" ]; then
  cat >> "$CHANGELOG" <<EOF

### [$TIMESTAMP] $ACTION
- **Action:** Git Commit
- **Message:** $TARGET
EOF
else
  cat >> "$CHANGELOG" <<EOF

### [$TIMESTAMP] $ACTION: \`$TARGET\`
- **Action:** $ACTION
- **File:** \`$TARGET\`
EOF
fi

exit 0
